### ISSUE TITLE
Aircon integration with Hassio

### ISSUE THREAD

**Issue by ck007max** [deiger/AirCon#18] opened 2020-05-28 12:30 UTC
Hello, I need your help. I follow your instructions and the webserver works on my AirCon. Now, I need to integrate it with Hassio. I put the following strings in my config file:
#AirCon
climate:
  - platform: mqtt
    name: "HiSense"
    current_temperature_topic: "hisense_ac/f_temp_in/status"
    current_temperature_template: "{{ value_json }}"
    fan_mode_command_topic: "hisense_ac/t_fan_speed/command"
    fan_mode_state_topic: "hisense_ac/t_fan_speed/status"
    fan_mode_state_template: "{{ value_json.t_fan_speed }}"
    fan_modes:
      - "auto"
      - "lower"
      - "low"
      - "medium"
      - "high"
      - "higher"
    mode_command_topic: "hisense_ac/t_work_mode/command"
    mode_state_topic: "hisense_ac/t_work_mode/status"
    mode_state_template: "{{ value_json.t_work_mode }}"
    modes:
      - "fan_only"
      - "heat"
      - "cool"
      - "dry"
      - "auto"
    power_command_topic: "hisense_ac/t_power/command"
    power_state_topic: "hisense_ac/t_power/status"
    power_state_template: "{{ value_json.t_power }}"
    swing_mode_state_topic: "hisense_ac/t_fan_power/status"
    swing_mode_command_topic: "hisense_ac/t_fan_power/command"
    swing_mode_state_template: "{{ value_json.t_fan_power }}"
    temperature_command_topic: "hisense_ac/t_temp/command"
    temperature_state_topic: "hisense_ac/t_temp/status"
    temperature_state_template: "{{ value_json.t_temp }}"
But I can't see and change the status of the aircon. What is wrong? 
How can I change the temperature from fahreneit to celsius?
Thank you

**Comment by deiger** [comment] 2020-05-28 13:47
You should set [temperature_unit](https://www.home-assistant.io/integrations/climate.mqtt/#temperature_unit) to `F`. Then Home Assistant should know internally how to convert the temperature.
The Hisense protocol is Fahrenheit only. Setting t_temptype changes the temperature displayed on the A/C screen, but the API continues to work in Fahrenheit. Given that t_temp is an integer, it is more accurate.

**Comment by deiger** [comment] 2020-05-28 14:37
Try using [this configuration file](../blob/master/hass/configuration.yaml).

**Comment by deiger** [comment] 2020-05-28 14:44
Duplicate of #12

**Closed** 2020-05-28 14:45 UTC
