### ISSUE TITLE
Home assistant integration

### ISSUE THREAD

**Issue by scaramatto** [deiger/AirCon#5] opened 2019-10-22 08:17 UTC
Thanks to this repository I was able to successfully start the services for all the air conditioners, I can command them with "Curl" but I can't integrate them in Home Assistant, the problem is the same as this ticket: "https://github.com/home-assistant/home-assistant/issues/27756 ". I have seen that many solve (for example with tasmota) setting "setOption19 1" this makes the home assistant automatically report the integration (autodiscover) "https://github.com/arendst/Sonoff-Tasmota/wiki/Home-Assistant ". Also I can't send commands with "Topic" and payolad. Sorry for the many questions and thanks for the support!

**Comment by snoopy12345** [comment] 2020-05-27 23:01
Would love to see it in homeassistant too! Would be outstanding and would donate for it!

**Comment by deiger** [comment] 2020-05-28 14:38
Try using [this configuration file](../blob/master/hass/configuration.yaml).

**Comment by deiger** [comment] 2020-05-28 14:42
Duplicate of #12

**Closed** 2020-05-28 14:45 UTC
